services:
  app-001:
    image: fpm-8.0.22
    # enviroment:
    #  - 'DOM_WEBROOT=/dom37176'
    #  - 'USE_JEMALLOC=0'
    working_dir: /public_html
    hostname: php-jclabserver
    volumes:
      - /usr/local/etc/fpm-pools/www.conf:/usr/local/etc/fpm-pools/www.conf
      - /usr/local/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      #- /usr/local/etc/php-fpm.d/zzz-logs.conf:/usr/local/etc/php-fpm.d/zzz-logs.conf  
      #- /usr/local/etc/php/conf.d:/usr/local/etc/php/conf.d
      - /usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
      - /var/www/jclabserver.xyz/public_html:/public_html:rslave
      - /var/www/jclabserver.xyz/mnt/:/mnt:rslave  
      #- ./current-fpm:/etc/php/current/fpm/
      # - ./current-pool.d/:/etc/php/current/fpm/pool.d/
      #- ./current-customer:/etc/php/current/fpm/user-conf.d/ 
      #- ./php8-fpm:/etc/php/8.0/fpm/
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/hostname:/etc/host-hostname:ro
      - /etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - /etc/msmtprc:/etc/msmtprc:ro
    #volumes:
    #  - type: bind
    #    source: /usr/local/etc/php/php.ini
    #    target: /usr/local/etc/php/php.ini:
    userns_mode: host
    network_mode: host
    restart: always
